/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    Usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    Usuarios: Usuario;
    media: Media;
    proyectos: Proyecto;
    categorias: Categoria;
    'correos-notificacion': CorreosNotificacion;
    'articulos-blog': ArticulosBlog;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    Usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    'correos-notificacion': CorreosNotificacionSelect<false> | CorreosNotificacionSelect<true>;
    'articulos-blog': ArticulosBlogSelect<false> | ArticulosBlogSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: Usuario & {
    collection: 'Usuarios';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Usuarios".
 */
export interface Usuario {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Gestión completa de proyectos de arquitectura, interiorismo y paisajismo
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: number;
  /**
   * Nombre descriptivo del proyecto
   */
  titulo: string;
  /**
   * Categoría principal del proyecto
   */
  tipo: number | Categoria;
  /**
   * Descripción detallada del proyecto, objetivos y características
   */
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Dirección o ubicación del proyecto
   */
  ubicacion?: string | null;
  /**
   * Estado actual del proyecto
   */
  estado?: ('desarrollo' | 'finalizado' | 'construccion' | 'aprobado') | null;
  /**
   * Marcar para exhibir este proyecto en la página de proyectos del sitio web
   */
  destacado?: boolean | null;
  /**
   * Colección de imágenes del proyecto
   */
  imagenes?:
    | {
        imagen: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Lista de características destacadas del proyecto
   */
  caracteristicas?:
    | {
        caracteristica: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categorías general de los proyectos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  /**
   * Nombre descriptivo de la categoría de proyecto
   */
  nombre: string;
  /**
   * Descripción detallada de los proyectos incluidos en esta categoría
   */
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestión de correos electrónicos para notificaciones del estudio
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "correos-notificacion".
 */
export interface CorreosNotificacion {
  id: number;
  /**
   * Nombre completo o identificador del destinatario
   */
  nombre: string;
  /**
   * Dirección de correo electrónico para recibir notificaciones
   */
  email: string;
  /**
   * Tipo específico de notificación que recibirá este correo
   */
  tipo_notificacion:
    | 'nuevo_proyecto'
    | 'consulta_cliente'
    | 'actualizacion_proyecto'
    | 'solicitud_servicio'
    | 'comentario_blog'
    | 'todas';
  /**
   * Nivel de prioridad para las notificaciones
   */
  prioridad?: ('alta' | 'media' | 'baja') | null;
  /**
   * Indica si este correo debe recibir notificaciones
   */
  activo?: boolean | null;
  /**
   * Notas adicionales sobre el propósito de este correo
   */
  descripcion?: string | null;
  /**
   * Número de teléfono opcional para contacto adicional
   */
  telefono?: string | null;
  /**
   * Área o departamento al que pertenece este contacto
   */
  departamento?: string | null;
  /**
   * Idioma preferido para recibir notificaciones
   */
  idioma_preferido?: ('es' | 'en' | 'pt') | null;
  /**
   * Configuración de horarios para recibir notificaciones
   */
  horario_notificacion?: {
    enviar_24_7?: boolean | null;
    /**
     * Formato 24h (ej: 09:00)
     */
    hora_inicio?: string | null;
    /**
     * Formato 24h (ej: 18:00)
     */
    hora_fin?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestión de artículos y publicaciones para el blog del estudio
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos-blog".
 */
export interface ArticulosBlog {
  id: number;
  /**
   * Título atractivo y descriptivo del artículo
   */
  titulo: string;
  /**
   * URL amigable para el artículo (se genera automáticamente)
   */
  slug?: string | null;
  /**
   * Breve resumen del contenido del artículo (máximo 250 caracteres)
   */
  resumen: string;
  /**
   * Contenido completo y detallado del artículo
   */
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Imagen principal que representa el artículo
   */
  imagen_destacada?: (number | null) | Media;
  /**
   * Nombre del arquitecto o diseñador que escribió el artículo
   */
  autor: string;
  /**
   * Categoría temática del artículo
   */
  categoria:
    | 'arquitectura-residencial'
    | 'interiorismo'
    | 'paisajismo'
    | 'diseno-marcas'
    | 'tendencias'
    | 'materiales'
    | 'sostenibilidad'
    | 'proyectos-destacados'
    | 'consejos-tips'
    | 'eventos-noticias';
  /**
   * Etiquetas para ayudar a los lectores a encontrar contenido relacionado
   */
  etiquetas?:
    | {
        etiqueta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Fecha en que se publicará el artículo
   */
  fecha_publicacion: string;
  /**
   * Estado actual del artículo
   */
  estado?: ('borrador' | 'revision' | 'publicado' | 'archivado') | null;
  /**
   * Marcar como artículo destacado en la página principal del blog
   */
  destacado?: boolean | null;
  /**
   * Tiempo estimado de lectura en minutos (se calcula automáticamente si se deja vacío)
   */
  lectura_estimada?: number | null;
  /**
   * Descripción corta para SEO (máximo 160 caracteres)
   */
  meta_descripcion?: string | null;
  /**
   * Palabras clave para optimización de motores de búsqueda
   */
  palabras_clave?:
    | {
        palabra_clave: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Imágenes adicionales para ilustrar el contenido del artículo
   */
  imagenes_galeria?:
    | {
        imagen: number | Media;
        pie_de_foto?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Permitir que los lectores dejen comentarios en este artículo
   */
  permitir_comentarios?: boolean | null;
  /**
   * Contador de visitas al artículo
   */
  visitas?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'Usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'proyectos';
        value: number | Proyecto;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'correos-notificacion';
        value: number | CorreosNotificacion;
      } | null)
    | ({
        relationTo: 'articulos-blog';
        value: number | ArticulosBlog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'Usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'Usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  titulo?: T;
  tipo?: T;
  descripcion?: T;
  ubicacion?: T;
  estado?: T;
  destacado?: T;
  imagenes?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  caracteristicas?:
    | T
    | {
        caracteristica?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "correos-notificacion_select".
 */
export interface CorreosNotificacionSelect<T extends boolean = true> {
  nombre?: T;
  email?: T;
  tipo_notificacion?: T;
  prioridad?: T;
  activo?: T;
  descripcion?: T;
  telefono?: T;
  departamento?: T;
  idioma_preferido?: T;
  horario_notificacion?:
    | T
    | {
        enviar_24_7?: T;
        hora_inicio?: T;
        hora_fin?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos-blog_select".
 */
export interface ArticulosBlogSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumen?: T;
  contenido?: T;
  imagen_destacada?: T;
  autor?: T;
  categoria?: T;
  etiquetas?:
    | T
    | {
        etiqueta?: T;
        id?: T;
      };
  fecha_publicacion?: T;
  estado?: T;
  destacado?: T;
  lectura_estimada?: T;
  meta_descripcion?: T;
  palabras_clave?:
    | T
    | {
        palabra_clave?: T;
        id?: T;
      };
  imagenes_galeria?:
    | T
    | {
        imagen?: T;
        pie_de_foto?: T;
        id?: T;
      };
  permitir_comentarios?: T;
  visitas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}